[package]
name = "notegraf"
version = "0.0.1"
authors = ["Zixian Cai"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
serde_json = "1.0"
pulldown-cmark = "0.8"