[package]
name = "notegraf-web"
version = "0.0.1"
authors = ["Zixian Cai"]
edition = "2018"

[dependencies]
# pinned to a minor release because a beta version is used
actix-web = "4.0.0-beta.9"
notegraf = {path = "../notegraf"}