name: Build and upload container image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: x86_64-unknown-linux-musl
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SQLX_OFFLINE: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './notegraf-web/package-lock.json'
      - uses: caizixian/toolchain@v1.0.8
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ env.CARGO_BUILD_TARGET }}
      - run: sudo apt-get install -u musl-tools musl-dev libpq-dev protobuf-compiler
      - run: npm install
        working-directory: ./notegraf-web
      - run: npm run build
        working-directory: ./notegraf-web
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
